# Generated by Django 4.2.7 on 2023-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='store/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
